name: vas_flutter
description: "EcoTrack Flutter Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # ================= UI ICONS =================
  cupertino_icons: ^1.0.8

  # ================= FIREBASE =================
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  firebase_app_check: ^0.4.1+2

  # ================= STATE MANAGEMENT =================
  provider: ^6.1.5

  # ================= MEDIA =================
  image_picker: ^1.2.1

  # ================= MAPS & LOCATION (FROM HER PROJECT) =================
  google_maps_flutter: ^2.3.0
  geolocator: ^14.0.2

  # ================= FEEDBACK SYSTEM =================
  flutter_rating_bar: ^4.0.1

  # ================= AI CHAT DEPENDENCIES =================
  http: ^1.3.0
  intl: ^0.20.2
  animated_text_kit: ^4.2.3
  flutter_spinkit: ^5.2.1

  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

  fonts:
    - family: fontMain
      fonts:
        - asset: assets/fonta/Poppins-Regular.ttf
